# Generated by Django 5.2.17 on 2026-10-01 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('shops', '0002_shopproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selected_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='shops.shop'),
        ),
    ]
