# Generated by Django 5.2.17 on 2026-10-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_selected_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='selected_shop',
        ),
    ]
